server:
  servlet:
    context-path: /api/coupon

spring:
  application:
    name: coupon
  datasource:
    url: jdbc:h2:mem:coupon;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: coupon
    password: coupon-dev
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
